---
output: html_document
---


## Set working directory

```{r, eval=TRUE}
setwd("D:/ujjwal/Tutorial/DataScience/Imarticus/Group Projects/R-ImarticusProject")

```


## Include the libraries required

```{r, eval=FALSE}
# install.packages("huxtable")
# install.packages("dplyr")
# install.packages('caret')
library(caret)
library(dplyr)
```

## Import other source codes (will be required to do some operations)

```{r, eval=TRUE}
source("cleanData.R")
```

```{r, eval=TRUE}
# Assign the data file name here.

# DataFileName <- 'data\\Group Project on R-Data Set-4.csv'
DataFileName <- 'data\\Gropup Project for R-Data Set.csv'

raw_data <- read.csv(DataFileName, stringsAsFactors = TRUE)

# Make a copy of raw data 
dataset <- raw_data

# Let's see the data, how it looks
head(dataset)

# Summary of dataset will give us the picture how data is distributed.
summary(dataset)
```

## Let's list down all factors in the dataset
```{r, eval=TRUE}
names(Filter(is.factor, dataset))
```

## Find out how many NA's we need to deal with
```{r, eval=TRUE}
sumNA <- sum(is.na(dataset))
print (sumNA)

```

## Now we need to find which column has this single NA value

```{r, eval=TRUE}
if(sumNA > 1){
  processNA(dataset)
}
```

